"""add author columns

Revision ID: b80d68788988
Revises: 0081252cde22
Create Date: 2022-05-15 11:23:32.699933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b80d68788988'
down_revision = '0081252cde22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('author', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'author')
    # ### end Alembic commands ###
